# Generated by Django 3.0.5 on 2021-04-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(upload_to='image/')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
